// Pure card builders — TS port of src/keibamon_core/marts/form.py.
//
// Source of truth: the Python functions `build_horse_card` and
// `build_jockey_card`. The TS port must produce byte-identical JSON for any
// given input row set. Pinned by src/form/parity.test.ts against golden
// fixtures generated by tools/form/generate_parity_fixtures.py.
//
// These functions take already-PIT-filtered, already-sorted (newest-first) row
// arrays. The caller (queries.ts / index.ts) is responsible for the SQL.

import { pyRound2, pyRound3 } from "./round";

// --- Row shape (matches the D1 `form_starts` table; columns are nullable) ---
export interface FormStartRow {
  horse_name_key: string | null;
  horse_name: string | null;
  jockey_id: string | null;
  trainer_id: string | null;
  race_id: string | null;
  horse_number: number | null;
  available_at: string | null;
  race_date: string | null;
  racecourse: string | null;
  surface: string | null;
  distance_m: number | null;
  distance_band: string | null;
  going: string | null;
  going_wetness: number | null;
  is_wet: number | null; // publisher writes 0/1
  grade_label: string | null;
  field_size: number | null;
  finish_position: number | null;
  finish_time_seconds: number | null;
  margin: string | null;
  last_3f_seconds: number | null;
  last_3f_rank: number | null;
  win_odds: number | null;
  popularity: number | null;
  beat_market: number | null;
  style_signal: string | null;
}

export interface Split {
  starts: number;
  wins: number;
  top3: number;
  win_pct: number | null;
  top3_pct: number | null;
}

export interface HorseFormCardOk {
  status: "ok";
  horse_name: string | null;
  as_of: string | null;
  context_note: string;
  career: Split;
  recent_finishes: Partial<FormStartRow>[];
  by_surface: Record<string, Split>;
  by_distance_band: Record<string, Split>;
  by_wet: { wet: Split; dry: Split };
  style_profile: Record<string, number>;
  style_note: string;
  market_vs_result: { avg_beat_market: number | null; note: string | null };
}

export interface HorseFormCardNoHistory {
  status: "no_history";
  horse_name: string | null;
  as_of: string | null;
}

export type HorseFormCard = HorseFormCardOk | HorseFormCardNoHistory;

export interface JockeyRecentFinish {
  available_at: string | null;
  race_date: string | null;
  racecourse: string | null;
  horse_name: string | null;
  finish_position: number | null;
  win_odds: number | null;
  popularity: number | null;
  grade_label: string | null;
}

export interface JockeyCombo {
  // The combo key is spread into the entry as {[comboKey]: value}. We model it
  // as a flat record so JSON.stringify mirrors the Python dict shape.
  [key: string]: string | number;
}

export interface JockeyFormCardOk {
  status: "ok";
  jockey_id: string | null;
  as_of: string | null;
  context_note: string;
  career: Split;
  by_course: Record<string, Split>;
  recent: JockeyRecentFinish[];
  combos: {
    by_horse: JockeyCombo[];
    by_trainer: JockeyCombo[];
  };
}

export interface JockeyFormCardNoHistory {
  status: "no_history";
  jockey_id: string | null;
  as_of: string | null;
}

export type JockeyFormCard = JockeyFormCardOk | JockeyFormCardNoHistory;

// --- Internal helpers (Python parity) -------------------------------------

/** Python: `round(n/d, 3) if d else None` */
function _pct(n: number, d: number): number | null {
  return d ? pyRound3(n / d) : null;
}

/** Python: `def _split(rows)` — career aggregate from a row list. */
export function split(rows: FormStartRow[]): Split {
  const starts = rows.length;
  let wins = 0;
  let top3 = 0;
  for (const r of rows) {
    const f = r.finish_position;
    if (f === 1) wins++;
    // Python: `r.get("finish_position") and r["finish_position"] <= 3` —
    // truthy check excludes 0 / null / undefined. JS `f && f <= 3` matches.
    if (f && f <= 3) top3++;
  }
  return {
    starts,
    wins,
    top3,
    win_pct: _pct(wins, starts),
    top3_pct: _pct(top3, starts),
  };
}

/** Python: `def _by_key(rows, key)` — buckets by a single column. */
export function byKey(rows: FormStartRow[], key: keyof FormStartRow): Record<string, Split> {
  const buckets = new Map<string, FormStartRow[]>();
  for (const r of rows) {
    const k = r[key];
    if (k === null || k === undefined) continue;
    const sk = String(k);
    let arr = buckets.get(sk);
    if (!arr) {
      arr = [];
      buckets.set(sk, arr);
    }
    arr.push(r);
  }
  const out: Record<string, Split> = {};
  for (const [k, v] of buckets) out[k] = split(v);
  return out;
}

const RECENT_FINISH_KEYS = [
  "available_at", "race_date", "racecourse", "surface", "distance_m",
  "going", "grade_label", "field_size", "finish_position", "margin",
  "last_3f_seconds", "win_odds", "popularity", "style_signal",
] as const;

const JOCKEY_RECENT_KEYS = [
  "available_at", "race_date", "racecourse", "horse_name",
  "finish_position", "win_odds", "popularity", "grade_label",
] as const;

// --- Public card builders --------------------------------------------------

export function buildHorseCard(
  rows: FormStartRow[],
  horseName: string | null,
  asOf: string | null,
): HorseFormCard {
  if (rows.length === 0) {
    return { status: "no_history", horse_name: horseName, as_of: asOf };
  }

  const career = split(rows);
  const recent = rows.slice(0, 8).map((r) => {
    const out: Partial<FormStartRow> = {};
    for (const k of RECENT_FINISH_KEYS) (out as Record<string, unknown>)[k] = r[k] ?? null;
    return out;
  });

  // style_profile: top-10 rows, count by `style_signal || "unknown"`.
  const styleProfile: Record<string, number> = {};
  for (const r of rows.slice(0, 10)) {
    const s = r.style_signal || "unknown";
    styleProfile[s] = (styleProfile[s] ?? 0) + 1;
  }

  // Market-vs-result.
  const beats: number[] = [];
  for (const r of rows) {
    if (r.beat_market !== null && r.beat_market !== undefined) beats.push(r.beat_market);
  }
  const avgBeat = beats.length > 0 ? pyRound2(beats.reduce((a, b) => a + b, 0) / beats.length) : null;
  let note: string | null = null;
  if (avgBeat !== null) {
    if (avgBeat > 0.5) note = "tends to outrun odds";
    else if (avgBeat < -0.5) note = "tends to run to odds";
  }

  const byWet = {
    wet: split(rows.filter((r) => Boolean(r.is_wet))),
    dry: split(rows.filter((r) => !r.is_wet)),
  };

  return {
    status: "ok",
    horse_name: horseName ?? rows[0].horse_name ?? null,
    as_of: asOf,
    context_note: "Form context, not betting advice.",
    career,
    recent_finishes: recent,
    by_surface: byKey(rows, "surface"),
    by_distance_band: byKey(rows, "distance_band"),
    by_wet: byWet,
    style_profile: styleProfile,
    style_note: "Running style is a rough proxy from finish + closing split.",
    market_vs_result: { avg_beat_market: avgBeat, note },
  };
}

function topCombos(
  rows: FormStartRow[],
  comboKey: "horse_name_key" | "trainer_id",
  nameKey: "horse_name" | null,
  limit: number,
): JockeyCombo[] {
  const buckets = new Map<string, FormStartRow[]>();
  for (const r of rows) {
    const k = r[comboKey];
    if (!k) continue;
    const sk = String(k);
    let arr = buckets.get(sk);
    if (!arr) {
      arr = [];
      buckets.set(sk, arr);
    }
    arr.push(r);
  }
  const out: JockeyCombo[] = [];
  for (const [k, group] of buckets) {
    const entry: JockeyCombo = {
      [comboKey]: k,
      starts: group.length,
      wins: group.filter((g) => g.finish_position === 1).length,
    };
    if (nameKey) {
      const name = group[0][nameKey];
      if (name) entry[nameKey] = String(name);
    }
    out.push(entry);
  }
  out.sort((a, b) => (b.starts as number) - (a.starts as number));
  return out.slice(0, limit);
}

export function buildJockeyCard(
  rows: FormStartRow[],
  jockeyId: string | null,
  asOf: string | null,
): JockeyFormCard {
  if (rows.length === 0) {
    return { status: "no_history", jockey_id: jockeyId, as_of: asOf };
  }

  const career = split(rows);
  const byCourse = byKey(rows, "racecourse");
  const recent: JockeyRecentFinish[] = rows.slice(0, 10).map((r) => {
    const out: JockeyRecentFinish = {
      available_at: r.available_at ?? null,
      race_date: r.race_date ?? null,
      racecourse: r.racecourse ?? null,
      horse_name: r.horse_name ?? null,
      finish_position: r.finish_position ?? null,
      win_odds: r.win_odds ?? null,
      popularity: r.popularity ?? null,
      grade_label: r.grade_label ?? null,
    };
    return out;
  });

  return {
    status: "ok",
    jockey_id: jockeyId,
    as_of: asOf,
    context_note: "Jockey context, not betting advice.",
    career,
    by_course: byCourse,
    recent,
    combos: {
      by_horse: topCombos(rows, "horse_name_key", "horse_name", 5),
      by_trainer: topCombos(rows, "trainer_id", null, 5),
    },
  };
}
